# housing :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- group: sonarcloud.vars
- { name: id, value: housingxyz }
- { name: directory, value: housing }
- { name: terraform, value: .terraformup }
- { name: webapp, value: angular }

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/angular.yml
    - .azure/stages/deploy.yml
    - housing

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/stages/angular.yml
    - .azure/stages/deploy.yml
    - housing

stages:
- template: ../../.azure/stages/angular.yml
  parameters:
    id: $(id)
- template: ../../.azure/stages/deploy.yml
  parameters:
    id: $(id)
